eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: school-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/schools/**
        - id: students-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/students/**

management:
  tracing:
    sampling:
      probability: 1.0